services:
  web01:
    build:
      context: ./site1
      dockerfile: Dockerfile
    image: web01
    container_name: web01
    networks:
      - teste-rede
  web02:
    build:
      context: ./site2
      dockerfile: Dockerfile
    image: web02
    container_name: web02
    networks:
      - teste-rede
  web03:
    build:
      context: ./site3
      dockerfile: Dockerfile
    image: web03
    container_name: web03
    networks:
      - teste-rede
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: proxy
    container_name: proxy
    ports:
     - "8080:80"
    depends_on:
      - web01
      - web02
      - web03
    networks:
      - teste-rede
#Docker Networks
networks:
  teste-rede:
    driver: bridge